# Site settings
title: Ryan Finnie
description: Personal blog for Ryan Finnie
author: Ryan Finnie
twitter_via: fo0
baseurl: ""
url: "https://www.finnie.org"
permalink: /:year/:month/:day/:title/
git_web_base: https://github.com/rfinnie/jekyll-finnie/blob/HEAD/
top_links:
  - title: "Projects"
    sublinks:
    - {title: "Finnix", url: "https://www.finnix.org/"}
    - {title: "2ping", url: "https://www.finnie.org/software/2ping/"}
    - {title: "dsari", url: "https://github.com/rfinnie/dsari"}
  - title: "About"
    sublinks:
    - {title: "Twitter", url: "https://twitter.com/rfinnie"}
    - {title: "GitHub", url: "https://github.com/rfinnie"}
    - {title: "Debian", url: "https://qa.debian.org/developer.php?login=ryan@finnie.org"}
    - {title: "OpenPGP", url: "https://keyserver.ubuntu.com/pks/lookup?search=0x42e2c8de8c173ab102f52c6e7e60a3a686ae8d98&fingerprint=on&op=index"}
    - {title: "Launchpad", url: "https://launchpad.net/~fo0bar"}
keep_files:
  - .git
  - blog-media
include:
  - blog-media
cse_id: "015291346489371011935:ibw1sgqcayw"

# Build settings
markdown: kramdown
